version: '3'
services:
  checker:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./data:/data
    environment:
      - PACKAGE_NAME=gr.nikolasspyr.integritycheck
